// Traduction des noms de pays (retournés en anglais par football-data.org)
// vers le français. Les noms non listés (clubs, équipes non répertoriées)
// sont renvoyés tels quels.
const COUNTRY_NAMES_FR: Record<string, string> = {
  Germany: 'Allemagne',
  Spain: 'Espagne',
  England: 'Angleterre',
  Wales: 'Pays de Galles',
  Scotland: 'Écosse',
  'Northern Ireland': 'Irlande du Nord',
  'Republic of Ireland': 'Irlande',
  Ireland: 'Irlande',
  France: 'France',
  Italy: 'Italie',
  Portugal: 'Portugal',
  Netherlands: 'Pays-Bas',
  Belgium: 'Belgique',
  Switzerland: 'Suisse',
  Austria: 'Autriche',
  Croatia: 'Croatie',
  Serbia: 'Serbie',
  Poland: 'Pologne',
  Ukraine: 'Ukraine',
  Russia: 'Russie',
  Turkey: 'Turquie',
  Türkiye: 'Turquie',
  Greece: 'Grèce',
  Sweden: 'Suède',
  Norway: 'Norvège',
  Denmark: 'Danemark',
  Finland: 'Finlande',
  Iceland: 'Islande',
  'Czech Republic': 'République tchèque',
  Czechia: 'République tchèque',
  Slovakia: 'Slovaquie',
  Slovenia: 'Slovénie',
  Hungary: 'Hongrie',
  Romania: 'Roumanie',
  Bulgaria: 'Bulgarie',
  Bosnia: 'Bosnie-Herzégovine',
  'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
  Montenegro: 'Monténégro',
  'North Macedonia': 'Macédoine du Nord',
  Albania: 'Albanie',
  Kosovo: 'Kosovo',
  Georgia: 'Géorgie',
  Armenia: 'Arménie',
  Azerbaijan: 'Azerbaïdjan',
  Israel: 'Israël',
  Cyprus: 'Chypre',
  Malta: 'Malte',
  Luxembourg: 'Luxembourg',
  Estonia: 'Estonie',
  Latvia: 'Lettonie',
  Lithuania: 'Lituanie',
  Belarus: 'Biélorussie',
  Moldova: 'Moldavie',
  Andorra: 'Andorre',
  'San Marino': 'Saint-Marin',
  Liechtenstein: 'Liechtenstein',
  Gibraltar: 'Gibraltar',
  Kazakhstan: 'Kazakhstan',
  'Faroe Islands': 'Îles Féroé',

  Brazil: 'Brésil',
  Argentina: 'Argentine',
  Uruguay: 'Uruguay',
  Chile: 'Chili',
  Colombia: 'Colombie',
  Peru: 'Pérou',
  Ecuador: 'Équateur',
  Paraguay: 'Paraguay',
  Bolivia: 'Bolivie',
  Venezuela: 'Venezuela',

  'United States': 'États-Unis',
  USA: 'États-Unis',
  Mexico: 'Mexique',
  Canada: 'Canada',
  Jamaica: 'Jamaïque',
  'Costa Rica': 'Costa Rica',
  Panama: 'Panama',
  Honduras: 'Honduras',
  'El Salvador': 'Salvador',
  Guatemala: 'Guatemala',
  'Trinidad and Tobago': 'Trinité-et-Tobago',
  Haiti: 'Haïti',
  Curaçao: 'Curaçao',
  Curacao: 'Curaçao',
  Suriname: 'Suriname',

  Morocco: 'Maroc',
  Algeria: 'Algérie',
  Tunisia: 'Tunisie',
  Egypt: 'Égypte',
  Senegal: 'Sénégal',
  Nigeria: 'Nigeria',
  Ghana: 'Ghana',
  'Ivory Coast': 'Côte d\'Ivoire',
  "Côte d'Ivoire": "Côte d'Ivoire",
  Cameroon: 'Cameroun',
  Mali: 'Mali',
  'Burkina Faso': 'Burkina Faso',
  'Cape Verde': 'Cap-Vert',
  'South Africa': 'Afrique du Sud',
  Guinea: 'Guinée',
  'Guinea-Bissau': 'Guinée-Bissau',
  Gabon: 'Gabon',
  Zambia: 'Zambie',
  Angola: 'Angola',
  Mozambique: 'Mozambique',
  Uganda: 'Ouganda',
  Tanzania: 'Tanzanie',
  Kenya: 'Kenya',
  'DR Congo': 'RD Congo',
  'Congo DR': 'RD Congo',
  Congo: 'Congo',
  Benin: 'Bénin',
  Togo: 'Togo',
  Niger: 'Niger',
  Namibia: 'Namibie',
  Zimbabwe: 'Zimbabwe',
  Mauritania: 'Mauritanie',
  Libya: 'Libye',
  Sudan: 'Soudan',
  Ethiopia: 'Éthiopie',
  Comoros: 'Comores',
  Madagascar: 'Madagascar',
  Rwanda: 'Rwanda',
  Gambia: 'Gambie',
  'Sierra Leone': 'Sierra Leone',
  Liberia: 'Liberia',
  Eswatini: 'Eswatini',
  Botswana: 'Botswana',
  Malawi: 'Malawi',
  Chad: 'Tchad',

  Japan: 'Japon',
  'South Korea': 'Corée du Sud',
  'Korea Republic': 'Corée du Sud',
  'North Korea': 'Corée du Nord',
  'Korea DPR': 'Corée du Nord',
  China: 'Chine',
  'China PR': 'Chine',
  Australia: 'Australie',
  'New Zealand': 'Nouvelle-Zélande',
  Iran: 'Iran',
  IR: 'Iran',
  'IR Iran': 'Iran',
  'Saudi Arabia': 'Arabie saoudite',
  Qatar: 'Qatar',
  'United Arab Emirates': 'Émirats arabes unis',
  Iraq: 'Irak',
  Jordan: 'Jordanie',
  Lebanon: 'Liban',
  Syria: 'Syrie',
  Uzbekistan: 'Ouzbékistan',
  Oman: 'Oman',
  Bahrain: 'Bahreïn',
  Kuwait: 'Koweït',
  India: 'Inde',
  Thailand: 'Thaïlande',
  Vietnam: 'Vietnam',
  Indonesia: 'Indonésie',
  Malaysia: 'Malaisie',
  Philippines: 'Philippines',
  Kyrgyzstan: 'Kirghizistan',
  Tajikistan: 'Tadjikistan',
  Turkmenistan: 'Turkménistan',
  Palestine: 'Palestine',
  Yemen: 'Yémen',
  Bangladesh: 'Bangladesh',
  Nepal: 'Népal',
  Bhutan: 'Bhoutan',
  Myanmar: 'Birmanie',
  Cambodia: 'Cambodge',
  Laos: 'Laos',
  Mongolia: 'Mongolie',
  Singapore: 'Singapour',
  'Hong Kong': 'Hong Kong',
  'Chinese Taipei': 'Taipei chinois',
  Afghanistan: 'Afghanistan',
  'Papua New Guinea': 'Papouasie-Nouvelle-Guinée',
  Fiji: 'Fidji',
  Tahiti: 'Tahiti',
  'New Caledonia': 'Nouvelle-Calédonie',
  'Solomon Islands': 'Îles Salomon',
  Vanuatu: 'Vanuatu',
}

export function translateTeamName(name: string): string {
  return COUNTRY_NAMES_FR[name] ?? name
}
