// ============================================================
//  JEU « COMBINÉ » — banque de phrases (verbe + vocabulaire)
// ============================================================
//  Chaque phrase associe UN verbe (par son infinitif `v` et son
//  temps `vT`) et UN mot de vocabulaire (`nHe`). Les gabarits
//  `frT` / `heT` contiennent {V} (le verbe conjugué) et {N} (le
//  mot). Certaines phrases hébraïques intègrent directement le
//  mot dans la phrase (accord, état construit…) : c'est voulu.
//
//  Règles de grammaire suivies :
//   • sujet toujours au masculin singulier (accord des verbes) ;
//   • את ה{N} pour un COD défini, sans את si indéfini ;
//   • prépositions ב / ל / על ה / מ selon le sens ;
//   • verbes à préposition fixe (עזר ל, חיכה ל, התלונן על,
//     ביקר ב, שילם על, נפטר מ, התמודד עם…).
//
//  app.js filtre les phrases dont le verbe n'existe pas dans la
//  base, donc on peut en ajouter sans risque.
// ============================================================

const COMBINE_PHRASES_RAW = [
  { v: "להסגר", vT: "Passé", vFr: "s'est fermée", nHe: "חלון", nFr: "fenêtre", frT: "La {N} {V} à cause du vent.", heT: "ה{N} {V} בגלל הרוח." },
  { v: "להשבר", vT: "Passé", vFr: "s'est cassé", nHe: "מחשב", nFr: "ordinateur", frT: "L'{N} {V} ce matin sans raison.", heT: "ה{N} {V} הבוקר בלי סיבה." },
  { v: "להפתח", vT: "Passé", vFr: "s'est ouverte", nHe: "חלון", nFr: "fenêtre", frT: "La {N} {V} toute seule pendant la nuit.", heT: "ה{N} {V} לבד באמצע הלילה." },
  { v: "להרדם", vT: "Passé", vFr: "s'est endormi", nHe: "ארוחה", nFr: "repas", frT: "Après le {N}, il {V} sur le canapé.", heT: "אחרי ה{N} הוא {V} על הספה." },
  { v: "להעלם", vT: "Passé", vFr: "a disparu", nHe: "יער", nFr: "forêt", frT: "Le chien {V} dans la {N} sombre.", heT: "הכלב {V} ב{N} החשוך." },
  { v: "להשתעל", vT: "Présent", vFr: "tousse", nHe: "רופא", nFr: "médecin", frT: "Il {V} tellement que le {N} s'inquiète.", heT: "הוא {V} כל כך שה{N} דואג." },
  { v: "להתלונן", vT: "Présent", vFr: "se plaint", nHe: "משבר", nFr: "crise", frT: "Il {V} toujours de la {N} économique.", heT: "הוא תמיד {V} על ה{N} הכלכלי." },
  { v: "לשכנע", vT: "Passé", vFr: "a convaincu", nHe: "בדיחה", nFr: "blague", frT: "Il m'{V} grâce à une bonne {N}.", heT: "הוא {V} אותי בזכות {N} טובה." },
  { v: "לצבוע", vT: "Passé", vFr: "a peint", nHe: "חלון", nFr: "fenêtre", frT: "Il {V} la {N} en bleu ce matin.", heT: "הוא {V} את ה{N} בכחול הבוקר." },
  { v: "למשוך", vT: "Présent", vFr: "attire", nHe: "מטבח", nFr: "cuisine", frT: "Cette odeur {V} les chats vers la {N}.", heT: "הריח הזה {V} את החתולים ל{N}." },
  { v: "להציל", vT: "Passé", vFr: "a sauvé", nHe: "שריפה", nFr: "incendie", frT: "Le pompier {V} l'enfant de l'{N}.", heT: "הכבאי {V} את הילד מה{N}." },
  { v: "להסתיר", vT: "Présent", vFr: "cache", nHe: "מפתח", nFr: "clé", frT: "Il {V} la {N} sous le tapis.", heT: "הוא {V} את ה{N} מתחת לשטיח." },
  { v: "להתנצל", vT: "Passé", vFr: "s'est excusé", nHe: "ידיד", nFr: "ami", frT: "Après la dispute, il {V} auprès de son {N}.", heT: "אחרי הריב הוא {V} בפני ה{N}." },
  { v: "להודיע", vT: "Passé", vFr: "a prévenu", nHe: "כביש", nFr: "route", frT: "Le guide nous {V} du danger sur la {N}.", heT: "המדריך {V} לנו על הסכנה ב{N}." },
  { v: "לטפס", vT: "Présent", vFr: "grimpe", nHe: "הר", nFr: "montagne", frT: "L'enfant {V} sur la {N} sans aucune peur.", heT: "הילד {V} על ה{N} בלי שום פחד." },
  { v: "להיבהל", vT: "Passé", vFr: "a paniqué", nHe: "רחוב", nFr: "rue", frT: "Il {V} à cause du bruit dans la {N}.", heT: "הוא {V} בגלל הרעש ב{N}." },
  { v: "לשחרר", vT: "Présent", vFr: "libère", nHe: "סוס", nFr: "cheval", frT: "Le fermier {V} le {N} dans le champ.", heT: "האיכר {V} את ה{N} בשדה." },
  { v: "להציק", vT: "Présent", vFr: "embête", nHe: "ארוחה", nFr: "repas", frT: "Ce bruit m'{V} pendant tout le {N}.", heT: "הרעש הזה {V} לי במשך כל ה{N}." },
  { v: "לצרוח", vT: "Présent", vFr: "hurle", nHe: "רופא", nFr: "médecin", frT: "Le bébé {V} dès qu'il voit le {N}.", heT: "התינוק {V} ברגע שהוא רואה את ה{N}." },
  { v: "להכעיס", vT: "Présent", vFr: "énerve", nHe: "כביש", nFr: "route", frT: "Ce chauffeur m'{V} sur la {N} chaque matin.", heT: "הנהג הזה {V} אותי ב{N} כל בוקר." },
  { v: "למנוע", vT: "Passé", vFr: "a empêché", nHe: "משבר", nFr: "crise", frT: "Rien n'{V} la {N} cette année.", heT: "שום דבר לא {V} את ה{N} השנה." },
  { v: "לארגן", vT: "Présent", vFr: "organise", nHe: "גינה", nFr: "jardin", frT: "Il {V} une grande fête dans le {N}.", heT: "הוא {V} מסיבה גדולה ב{N}." },
  { v: "להפוך", vT: "Présent", vFr: "transforme", nHe: "משרד", nFr: "bureau", frT: "Il {V} le vieux garage en {N}.", heT: "הוא {V} את המוסך הישן ל{N}." },
  { v: "להפטר", vT: "Présent", vFr: "se débarrasse", nHe: "מעיל", nFr: "manteau", frT: "Il {V} enfin de son vieux {N}.", heT: "הוא סוף סוף {V} מה{N} הישן." },
  { v: "להשבע", vT: "Présent", vFr: "jure", nHe: "יער", nFr: "forêt", frT: "Il {V} qu'il a vu un loup dans la {N}.", heT: "הוא {V} שהוא ראה זאב ב{N}." },
  { v: "להעלב", vT: "Présent", vFr: "se vexe", nHe: "בדיחה", nFr: "blague", frT: "Il {V} pour la moindre {N}.", heT: "הוא {V} מכל {N} קטנה." },
  { v: "להתייחס", vT: "Présent", vFr: "considère", nHe: "תוצאה", nFr: "résultat", frT: "Il {V} chaque {N} comme une leçon.", heT: "הוא {V} לכל {N} כמו שיעור." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "מחמאה", nFr: "compliment", frT: "Il {V} toujours un {N} sincère à ses collègues.", heT: "הוא תמיד {V} {N} כנה לעמיתים שלו." },
  { v: "לקבל", vT: "Passé", vFr: "a reçu", nHe: "תוצאה", nFr: "résultat", frT: "Il {V} un excellent {N} à l'examen.", heT: "הוא {V} {N} מצוינת במבחן." },
  { v: "לשלם", vT: "Présent", vFr: "paie", nHe: "ביטוח", nFr: "assurance", frT: "Il {V} l'{N} de sa voiture chaque mois.", heT: "הוא {V} את ה{N} של המכונית כל חודש." },
  { v: "לקרוא", vT: "Présent", vFr: "lit", nHe: "עיתון", nFr: "journal", frT: "Chaque matin, il {V} le {N} dans le bus.", heT: "כל בוקר הוא {V} את ה{N} באוטובוס." },
  { v: "לספר", vT: "Présent", vFr: "raconte", nHe: "בדיחה", nFr: "blague", frT: "Il {V} une {N} très drôle à table.", heT: "הוא {V} {N} מאוד מצחיקה ליד השולחן." },
  { v: "להראות", vHe: "מראה", vT: "Présent", vFr: "montre", nHe: "ירך", nFr: "hanche", frT: "Il {V} sa {N} blessée au médecin.", heT: "הוא {V} את ה{N} הפצועה לרופא." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "כפתור", nFr: "bouton", frT: "Il {V} le {N} de la lumière dans le noir.", heT: "הוא {V} את ה{N} של האור בחושך." },
  { v: "ללכת", vT: "Présent", vFr: "marche", nHe: "החלמה", nFr: "guérison", frT: "Après une longue {N}, il {V} de nouveau.", heT: "אחרי {N} ארוכה הוא {V} שוב." },
  { v: "לבקר", vT: "Présent", vFr: "visite", nHe: "בית אבות", nFr: "maison de retraite", frT: "Chaque dimanche, il {V} son grand-père à la {N}.", heT: "כל יום ראשון הוא {V} את סבא שלו ב{N}." },
  { v: "למצוא", vT: "Passé", vFr: "a trouvé", nHe: "משבר", nFr: "crise", frT: "Il {V} une solution après une longue {N}.", heT: "הוא {V} פתרון אחרי {N} ארוך." },
  { v: "לשלוח", vT: "Passé", vFr: "a envoyé", nHe: "מכתב", nFr: "lettre", frT: "Il {V} une longue {N} à sa famille.", heT: "הוא {V} {N} ארוך למשפחה שלו." },
  { v: "ללבוש", vT: "Présent", vFr: "porte", nHe: "מעיל", nFr: "manteau", frT: "Il {V} un {N} chaud à cause de la neige.", heT: "הוא {V} {N} חם בגלל השלג." },
  { v: "לקנות", vT: "Passé", vFr: "a acheté", nHe: "מזוודה", nFr: "valise", frT: "Il {V} une nouvelle {N} pour son voyage.", heT: "הוא {V} {N} חדשה לטיול שלו." },
  { v: "לשכוח", vT: "Présent", vFr: "oublie", nHe: "משרד", nFr: "bureau", frT: "Il {V} souvent son parapluie au {N}.", heT: "הוא לעתים קרובות {V} את המטרייה שלו ב{N}." },
  { v: "להסביר", vT: "Présent", vFr: "explique", nHe: "שפה", nFr: "langue", frT: "Le professeur {V} la {N} avec beaucoup de patience.", heT: "המורה {V} את ה{N} בהרבה סבלנות." },
  { v: "לבשל", vT: "Présent", vFr: "cuisine", nHe: "ארוחה", nFr: "repas", frT: "Chaque soir, il {V} un bon {N} pour ses enfants.", heT: "כל ערב הוא {V} {N} טובה לילדים שלו." },
  { v: "לנהוג", vT: "Présent", vFr: "conduit", nHe: "עיר", nFr: "ville", frT: "Il {V} prudemment dans la grande {N}.", heT: "הוא {V} בזהירות ב{N} הגדולה." },
  { v: "לראות", vT: "Passé", vFr: "a regardé", nHe: "סרט", nFr: "film", frT: "Hier soir, il {V} un {N} passionnant.", heT: "אתמול בערב הוא {V} {N} מרתק." },
  { v: "למכור", vT: "Passé", vFr: "a vendu", nHe: "מחשב", nFr: "ordinateur", frT: "Il {V} son vieil {N} sur internet.", heT: "הוא {V} את ה{N} הישן שלו באינטרנט." },
  { v: "לכתוב", vT: "Présent", vFr: "écrit", nHe: "מחברת", nFr: "cahier", frT: "Il {V} une belle histoire dans son {N}.", heT: "הוא {V} סיפור יפה ב{N} שלו." },
  { v: "לשחק", vT: "Présent", vFr: "joue", nHe: "גינה", nFr: "jardin", frT: "Il {V} au ballon dans le {N}.", heT: "הוא {V} בכדור ב{N}." },
  { v: "לצחוק", vT: "Présent", vFr: "rit", nHe: "סרט", nFr: "film", frT: "Il {V} pendant tout le {N}.", heT: "הוא {V} במשך כל ה{N}." },
  { v: "לבכות", vT: "Présent", vFr: "pleure", nHe: "סיפור", nFr: "histoire", frT: "Il {V} à la fin de cette {N} triste.", heT: "הוא {V} בסוף ה{N} העצוב." },
  { v: "לשאול", vT: "Présent", vFr: "demande", nHe: "עיר", nFr: "ville", frT: "Il {V} son chemin dans la grande {N}.", heT: "הוא {V} את הדרך ב{N} הגדולה." },
  { v: "לנוח", vT: "Présent", vFr: "se repose", nHe: "גינה", nFr: "jardin", frT: "Après une longue promenade, il {V} dans le {N}.", heT: "אחרי טיול ארוך הוא {V} ב{N}." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "מטבח", nFr: "cuisine", frT: "Il {V} le sol de la {N}.", heT: "הוא {V} את רצפת ה{N}." },
  { v: "להתגרש", vT: "Présent", vFr: "divorce", nHe: "משבר", nFr: "crise", frT: "Après une longue {N}, il {V} enfin.", heT: "אחרי {N} ארוך הוא סוף סוף {V}." },
  { v: "להתמודד", vT: "Présent", vFr: "affronte", nHe: "משבר", nFr: "crise", frT: "Il {V} la {N} avec beaucoup de courage.", heT: "הוא {V} עם ה{N} בהרבה אומץ." },
  { v: "להקיא", vT: "Passé", vFr: "a vomi", nHe: "ארוחה", nFr: "repas", frT: "Il {V} à cause du mauvais {N}.", heT: "הוא {V} בגלל ה{N} הגרועה." },
  { v: "לגרור", vT: "Présent", vFr: "traine", nHe: "מזוודה", nFr: "valise", frT: "Il {V} sa lourde {N} dans la gare.", heT: "הוא {V} את ה{N} הכבדה בתחנה." },
  { v: "לחתוך", vT: "Présent", vFr: "coupe", nHe: "עוגה", nFr: "gâteau", frT: "Il {V} le {N} en huit parts égales.", heT: "הוא {V} את ה{N} לשמונה חלקים שווים." },
  { v: "לסדר", vT: "Présent", vFr: "range", nHe: "משרד", nFr: "bureau", frT: "Il {V} les papiers dans le {N}.", heT: "הוא {V} את הניירות ב{N}." },
  { v: "לפתוח", vT: "Présent", vFr: "ouvre", nHe: "מכתב", nFr: "lettre", frT: "Il {V} la {N} avec beaucoup d'impatience.", heT: "הוא {V} את ה{N} בהרבה קוצר רוח." },
  { v: "לזרוק", vT: "Présent", vFr: "jette", nHe: "נעליים", nFr: "chaussures", frT: "Il {V} ses vieilles {N} à la poubelle.", heT: "הוא {V} את ה{N} הישנות לפח." },
  { v: "ללבוש", vT: "Présent", vFr: "porte", nHe: "כובע", nFr: "chapeau", frT: "Il {V} un beau {N} sous le soleil.", heT: "הוא {V} {N} יפה מתחת לשמש." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "מצלמה", nFr: "appareil photo", frT: "Il {V} un {N} cher au magasin.", heT: "הוא {V} {N} יקרה בחנות." },
  { v: "לשתות", vT: "Présent", vFr: "boit", nHe: "רכבת", nFr: "train", frT: "Il {V} un café dans le {N} du matin.", heT: "הוא {V} קפה ב{N} של הבוקר." },
  { v: "לישון", vT: "Présent", vFr: "dort", nHe: "רחוב", nFr: "rue", frT: "Il {V} mal à cause du bruit de la {N}.", heT: "הוא {V} רע בגלל הרעש של ה{N}." },
  { v: "לשלוח", vT: "Présent", vFr: "envoie", nHe: "הר", nFr: "montagne", frT: "Il {V} une belle photo de la {N}.", heT: "הוא {V} תמונה יפה של ה{N}." },
  { v: "לשיר", vT: "Présent", vFr: "chante", nHe: "גינה", nFr: "jardin", frT: "Il {V} à la fête dans le {N}.", heT: "הוא {V} במסיבה ב{N}." },
  { v: "לפגוש", vT: "Présent", vFr: "rencontre", nHe: "כבאי", nFr: "pompier", frT: "Il {V} un vieux {N} au marché.", heT: "הוא {V} {N} זקן בשוק." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "עט", nFr: "stylo", frT: "Il {V} un {N} neuf à son fils.", heT: "הוא {V} {N} חדש לבן שלו." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "ידיד", nFr: "ami", frT: "Il {V} son {N} devant le cinéma.", heT: "הוא {V} ל{N} מול הקולנוע." },
  { v: "ללמוד", vT: "Présent", vFr: "étudie", nHe: "חומר", nFr: "matière", frT: "Il {V} une {N} difficile à l'université.", heT: "הוא {V} {N} קשה באוניברסיטה." },
  { v: "להכין", vT: "Présent", vFr: "prépare", nHe: "ארוחה", nFr: "repas", frT: "Chaque soir, il {V} un bon {N} pour sa famille.", heT: "כל ערב הוא {V} {N} טובה למשפחה שלו." },
  { v: "להסביר", vT: "Présent", vFr: "explique", nHe: "עיקרון", nFr: "principe", frT: "Le professeur {V} le {N} avec un exemple.", heT: "המורה {V} את ה{N} עם דוגמה." },
  { v: "להראות", vHe: "מראה", vT: "Présent", vFr: "montre", nHe: "אגודל", nFr: "pouce", frT: "Il {V} son {N} blessé au médecin.", heT: "הוא {V} את ה{N} הפצוע לרופא." },
  { v: "לחתוך", vT: "Présent", vFr: "coupe", nHe: "אצבע", nFr: "doigt", frT: "Il {V} son {N} avec le couteau.", heT: "הוא {V} את ה{N} עם הסכין." },
  { v: "לשחרר", vT: "Présent", vFr: "libère", nHe: "גינה", nFr: "jardin", frT: "Il {V} les oiseaux dans le {N}.", heT: "הוא {V} את הציפורים ב{N}." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "פרה", nFr: "vache", frT: "Il {V} une grosse {N} dans le champ.", heT: "הוא {V} פרה גדולה בשדה." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "אריה", nFr: "lion", frT: "Il {V} le {N} au zoo avec ses enfants.", heT: "הוא {V} את ה{N} בגן החיות עם הילדים." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "גנב", nFr: "voleur", frT: "Le policier {V} le {N} dans toute la ville.", heT: "השוטר {V} את ה{N} בכל העיר." },
  { v: "לאהוב", vT: "Présent", vFr: "aime", nHe: "מלך", nFr: "roi", frT: "Le peuple {V} son {N} juste et sage.", heT: "העם {V} את ה{N} הצדיק והחכם." },
  { v: "לעזור", vT: "Présent", vFr: "aide", nHe: "שכן", nFr: "voisin", frT: "Il {V} son {N} à porter les sacs lourds.", heT: "הוא {V} ל{N} לשאת את השקיות הכבדות." },
  { v: "לדבר", vT: "Présent", vFr: "parle", nHe: "מנהל", nFr: "patron", frT: "Il {V} avec son {N} dans le bureau.", heT: "הוא {V} עם ה{N} במשרד." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "אורז", nFr: "riz", frT: "Il {V} du {N} avec du poulet grillé.", heT: "הוא {V} {N} עם עוף צלוי." },
  { v: "להכין", vT: "Présent", vFr: "prépare", nHe: "מרק", nFr: "soupe", frT: "En hiver, il {V} une {N} chaude et épaisse.", heT: "בחורף הוא {V} {N} חם וסמיך." },
  { v: "להוסיף", vT: "Présent", vFr: "ajoute", nHe: "מלח", nFr: "sel", frT: "Il {V} un peu de {N} dans la soupe.", heT: "הוא {V} קצת {N} למרק." },
  { v: "לשבור", vT: "Présent", vFr: "casse", nHe: "כוס", nFr: "verre", frT: "Il {V} un {N} en lavant la vaisselle.", heT: "הוא {V} כוס תוך כדי שטיפת הכלים." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "סכין", nFr: "couteau", frT: "Il {V} le {N} pour couper le pain.", heT: "הוא {V} את ה{N} כדי לחתוך את הלחם." },
  { v: "לשים", vT: "Présent", vFr: "pose", nHe: "מזלג", nFr: "fourchette", frT: "Il {V} la {N} à côté de l'assiette.", heT: "הוא {V} את ה{N} ליד הצלחת." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "שטיח", nFr: "tapis", frT: "Il {V} un beau {N} coloré au marché.", heT: "הוא {V} {N} יפה וצבעוני בשוק." },
  { v: "לשבור", vT: "Présent", vFr: "casse", nHe: "מנורה", nFr: "lampe", frT: "Il {V} la {N} sans faire exprès.", heT: "הוא {V} את ה{N} בלי כוונה." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "מעלית", nFr: "ascenseur", frT: "Il {V} l'{N} au rez-de-chaussée.", heT: "הוא {V} ל{N} בקומת הקרקע." },
  { v: "לישון", vT: "Présent", vFr: "dort", nHe: "גג", nFr: "toit", frT: "Le chat {V} tranquillement sur le {N}.", heT: "החתול {V} בשקט על ה{N}." },
  { v: "לצבוע", vT: "Présent", vFr: "peint", nHe: "חומה", nFr: "mur", frT: "Il {V} le {N} du salon en blanc.", heT: "הוא {V} את ה{N} של הסלון בלבן." },
  { v: "לשכוח", vT: "Présent", vFr: "oublie", nHe: "מטריה", nFr: "parapluie", frT: "Il {V} son {N} dans le bus chaque hiver.", heT: "הוא {V} את ה{N} באוטובוס כל חורף." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "משקפיים", nFr: "lunettes", frT: "Il {V} ses {N} partout dans la maison.", heT: "הוא {V} את ה{N} בכל הבית." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "טבעת", nFr: "bague", frT: "Il {V} une {N} en or à sa fiancée.", heT: "הוא {V} {N} מזהב לארוסה שלו." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "שרשרת", nFr: "collier", frT: "Il {V} un joli {N} pour l'anniversaire.", heT: "הוא {V} {N} יפה ליום ההולדת." },
  { v: "ללבוש", vT: "Présent", vFr: "porte", nHe: "סוודר", nFr: "pull", frT: "Il {V} un {N} chaud quand il fait froid.", heT: "הוא {V} {N} חם כשקר." },
  { v: "למכור", vT: "Présent", vFr: "vend", nHe: "ז׳קט", nFr: "veste", frT: "Il {V} une vieille {N} sur internet.", heT: "הוא {V} ז׳קט ישן באינטרנט." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "מכנסיים", nFr: "pantalon", frT: "Il {V} un {N} neuf pour le mariage.", heT: "הוא {V} מכנסיים חדשים לחתונה." },
  { v: "למכור", vT: "Présent", vFr: "vend", nHe: "חצאית", nFr: "jupe", frT: "Il {V} une belle {N} dans son magasin.", heT: "הוא {V} חצאית יפה בחנות שלו." },
  { v: "לראות", vT: "Présent", vFr: "regarde", nHe: "ירח", nFr: "lune", frT: "Le soir, il {V} la {N} depuis le balcon.", heT: "בערב הוא {V} את ה{N} מהמרפסת." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "ענן", nFr: "nuage", frT: "Il {V} un gros {N} noir dans le ciel.", heT: "הוא {V} ענן שחור גדול בשמיים." },
  { v: "לשחק", vT: "Présent", vFr: "joue", nHe: "חול", nFr: "sable", frT: "L'enfant {V} dans le {N} à la plage.", heT: "הילד {V} בחול בחוף." },
  { v: "למצוא", vT: "Présent", vFr: "trouve", nHe: "עלה", nFr: "feuille", frT: "En automne, il {V} une {N} rouge par terre.", heT: "בסתיו הוא {V} עלה אדום על הרצפה." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "מאפייה", nFr: "boulangerie", frT: "Chaque matin, il {V} du pain frais à la {N}.", heT: "כל בוקר הוא {V} לחם טרי ב{N}." },
  { v: "לשלוח", vT: "Présent", vFr: "envoie", nHe: "דואר", nFr: "poste", frT: "Il {V} un colis important à la {N}.", heT: "הוא {V} חבילה חשובה ב{N}." },
  { v: "לאהוב", vT: "Présent", vFr: "aime", nHe: "ארץ", nFr: "pays", frT: "Il {V} beaucoup son {N} natal.", heT: "הוא {V} מאוד את ה{N} שלו." },
  { v: "לקנות", vT: "Passé", vFr: "a acheté", nHe: "ציור", nFr: "peinture", frT: "Il {V} une {N} ancienne au marché aux puces.", heT: "הוא {V} ציור עתיק בשוק הפשפשים." },
  { v: "לזרוק", vT: "Présent", vFr: "jette", nHe: "אבן", nFr: "pierre", frT: "Il {V} une {N} dans la rivière calme.", heT: "הוא {V} אבן לנהר השקט." },
  { v: "למכור", vT: "Présent", vFr: "vend", nHe: "זהב", nFr: "or", frT: "Il {V} une montre en {N} au bijoutier.", heT: "הוא {V} שעון מ{N} לצורף." },
  { v: "להוסיף", vT: "Présent", vFr: "ajoute", nHe: "שמן", nFr: "huile", frT: "Il {V} de l'{N} dans la poêle brûlante.", heT: "הוא {V} {N} למחבת הלוהטת." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "עור", nFr: "cuir", frT: "Il {V} un sac en {N} véritable.", heT: "הוא {V} תיק מ{N} אמיתי." },
  { v: "לחזור", vT: "Présent", vFr: "revient", nHe: "עיר", nFr: "ville", frT: "Chaque soir, il {V} de la {N} en train.", heT: "כל ערב הוא {V} מה{N} ברכבת." },
  { v: "להמין", vT: "Présent", vFr: "croit", nHe: "סיפור", nFr: "histoire", frT: "Il {V} chaque {N} de son ami naïvement.", heT: "הוא {V} לכל {N} של החבר שלו בתמימות." },
  { v: "להסתיר", vT: "Présent", vFr: "cache", nHe: "טבעת", nFr: "bague", frT: "Il {V} la {N} dans un tiroir secret.", heT: "הוא {V} את ה{N} במגירה סודית." },
  { v: "להתלונן", vT: "Présent", vFr: "se plaint", nHe: "שכן", nFr: "voisin", frT: "Il {V} sans cesse de son {N} bruyant.", heT: "הוא {V} כל הזמן על ה{N} הרעשן." },
  { v: "להעלם", vT: "Passé", vFr: "a disparu", nHe: "ממון", nFr: "argent", frT: "L'{N} {V} du coffre pendant la nuit.", heT: "ה{N} {V} מהכספת במהלך הלילה." },
  { v: "לטפס", vT: "Présent", vFr: "grimpe", nHe: "גג", nFr: "toit", frT: "Le chat {V} sur le {N} du voisin.", heT: "החתול {V} על ה{N} של השכן." },
  { v: "לשחרר", vT: "Présent", vFr: "libère", nHe: "אריה", nFr: "lion", frT: "Le gardien {V} le {N} dans un grand enclos.", heT: "השומר {V} את ה{N} למכלאה גדולה." },
  { v: "לצבוע", vT: "Présent", vFr: "peint", nHe: "גג", nFr: "toit", frT: "Il {V} le {N} rouge de la vieille maison.", heT: "הוא {V} את ה{N} האדום של הבית הישן." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "כוס", nFr: "verre", frT: "Il {V} chaque {N} après le dîner.", heT: "הוא {V} כל כוס אחרי ארוחת הערב." },
  { v: "לעלות", vT: "Présent", vFr: "monte", nHe: "מעלית", nFr: "ascenseur", frT: "Il {V} dans l'{N} jusqu'au dernier étage.", heT: "הוא {V} ב{N} עד הקומה האחרונה." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "עיתון", nFr: "journal", frT: "Il {V} le {N} du matin à son père.", heT: "הוא {V} את ה{N} של הבוקר לאבא שלו." },
  { v: "לבשל", vT: "Présent", vFr: "cuisine", nHe: "מרק", nFr: "soupe", frT: "Il {V} une {N} de légumes pour ce soir.", heT: "הוא {V} {N} ירקות להערב." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "מנורה", nFr: "lampe", frT: "Il {V} une {N} moderne pour le salon.", heT: "הוא {V} {N} מודרנית לסלון." },

  // ============================================================
  //  Ajout : 100 phrases supplémentaires (mots & verbes variés)
  // ============================================================
  // — Nouveaux mots : métiers & personnages —
  { v: "לאהוב", vT: "Présent", vFr: "aime", nHe: "מנהיג", nFr: "chef", frT: "Le peuple {V} son {N} courageux.", heT: "העם {V} את ה{N} האמיץ." },
  { v: "לבשל", vT: "Présent", vFr: "cuisine", nHe: "טבח", nFr: "cuisinier", frT: "Le {N} {V} pour tous les clients du restaurant.", heT: "ה{N} {V} לכל הלקוחות של המסעדה." },
  { v: "לארגן", vT: "Présent", vFr: "organise", nHe: "גנן", nFr: "jardinier", frT: "Le {N} {V} le jardin avant l'été.", heT: "ה{N} {V} את הגינה לפני הקיץ." },
  { v: "לנוח", vT: "Présent", vFr: "se repose", nHe: "רועה", nFr: "berger", frT: "Le {N} {V} sous un grand arbre.", heT: "ה{N} {V} מתחת לעץ גדול." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "טייס", nFr: "pilote", frT: "Il {V} le {N} devant le grand avion.", heT: "הוא {V} את ה{N} מול המטוס הגדול." },
  { v: "להראות", vHe: "מראה", vT: "Présent", vFr: "montre", nHe: "צייר", nFr: "peintre", frT: "Le {N} {V} son tableau au public.", heT: "ה{N} {V} את הציור שלו לקהל." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "תייר", nFr: "touriste", frT: "Le {N} {V} son chemin dans la vieille ville.", heT: "ה{N} {V} את הדרך בעיר העתיקה." },
  { v: "לשלם", vT: "Présent", vFr: "paie", nHe: "לקוח", nFr: "client", frT: "Le {N} {V} l'addition au restaurant.", heT: "ה{N} {V} את החשבון במסעדה." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "מלאך", nFr: "ange", frT: "Dans son rêve, il {V} un {N} avec des ailes.", heT: "בחלום שלו הוא {V} מלאך עם כנפיים." },
  { v: "לפגוש", vT: "Présent", vFr: "rencontre", nHe: "כבאי", nFr: "pompier", frT: "Devant l'immeuble en feu, il {V} un {N} fatigué.", heT: "מול הבניין הבוער הוא {V} כבאי עייף." },
  // — Nouveaux mots : animaux —
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "שועל", nFr: "renard", frT: "Il {V} un {N} roux dans la forêt.", heT: "הוא {V} שועל אדמוני ביער." },
  { v: "לפגוש", vT: "Présent", vFr: "rencontre", nHe: "זאב", nFr: "loup", frT: "Dans la forêt sombre, il {V} un {N} affamé.", heT: "ביער החשוך הוא {V} זאב רעב." },
  { v: "להציק", vT: "Présent", vFr: "embête", nHe: "זבוב", nFr: "mouche", frT: "Une petite {N} m'{V} pendant tout le repas.", heT: "זבוב קטן {V} לי במשך כל הארוחה." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "ברווז", nFr: "canard", frT: "Il {V} un {N} qui nage sur le lac.", heT: "הוא {V} ברווז ששוחה על האגם." },
  { v: "לשיר", vT: "Présent", vFr: "chante", nHe: "תרנגול", nFr: "coq", frT: "Le {N} {V} très tôt le matin.", heT: "ה{N} {V} מוקדם מאוד בבוקר." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "כבשה", nFr: "mouton", frT: "Le berger {V} le {N} perdu dans les collines.", heT: "הרועה {V} את ה{N} האבודה בגבעות." },
  { v: "לשתות", vT: "Présent", vFr: "boit", nHe: "גמל", nFr: "chameau", frT: "Dans le désert, le {N} {V} beaucoup d'eau.", heT: "במדבר ה{N} {V} הרבה מים." },
  { v: "ללכת", vT: "Présent", vFr: "marche", nHe: "צב", nFr: "tortue", frT: "La {N} {V} très lentement dans le jardin.", heT: "ה{N} {V} לאט מאוד בגינה." },
  { v: "לצרוח", vT: "Présent", vFr: "hurle", nHe: "אריה", nFr: "lion", frT: "Le {N} {V} très fort pendant la nuit.", heT: "ה{N} {V} חזק מאוד במהלך הלילה." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "פרה", nFr: "vache", frT: "Le fermier {V} la {N} perdue dans le champ.", heT: "האיכר {V} את ה{N} האבודה בשדה." },
  // — Nouveaux mots : fruits & cuisine —
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "אגס", nFr: "poire", frT: "Au dessert, il {V} une {N} bien mûre.", heT: "בקינוח הוא {V} אגס בשל." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "ענב", nFr: "raisin", frT: "Il {V} un {N} sucré du jardin.", heT: "הוא {V} ענב מתוק מהגינה." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "תות", nFr: "fraise", frT: "L'enfant {V} une {N} rouge et sucrée.", heT: "הילד {V} תות אדום ומתוק." },
  { v: "להוסיף", vT: "Présent", vFr: "ajoute", nHe: "שקד", nFr: "amande", frT: "Il {V} une {N} sur le gâteau au chocolat.", heT: "הוא {V} שקד על עוגת השוקולד." },
  { v: "לחתוך", vT: "Présent", vFr: "coupe", nHe: "גזר", nFr: "carotte", frT: "Il {V} une {N} pour la soupe du soir.", heT: "הוא {V} גזר למרק של הערב." },
  { v: "לחתוך", vT: "Présent", vFr: "coupe", nHe: "עגבנייה", nFr: "tomate", frT: "Il {V} une {N} pour la salade.", heT: "הוא {V} עגבנייה לסלט." },
  { v: "לחתוך", vT: "Présent", vFr: "coupe", nHe: "בצל", nFr: "oignon", frT: "Il {V} un {N} et pleure un peu.", heT: "הוא {V} בצל ובוכה קצת." },
  { v: "להוסיף", vT: "Présent", vFr: "ajoute", nHe: "שום", nFr: "ail", frT: "Il {V} de l'{N} dans la sauce tomate.", heT: "הוא {V} שום לרוטב העגבניות." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "חסה", nFr: "laitue", frT: "Il {V} la {N} avant de préparer la salade.", heT: "הוא {V} את החסה לפני הכנת הסלט." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "קמח", nFr: "farine", frT: "Pour le gâteau, il {V} de la {N} et du sucre.", heT: "לעוגה הוא {V} קמח וסוכר." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "ריבה", nFr: "confiture", frT: "Le matin, il {V} du pain avec de la {N}.", heT: "בבוקר הוא {V} לחם עם ריבה." },
  { v: "להכין", vT: "Présent", vFr: "prépare", nHe: "פאי", nFr: "tarte", frT: "Pour l'anniversaire, il {V} une {N} aux pommes.", heT: "ליום ההולדת הוא {V} פאי תפוחים." },
  // — Nouveaux mots : lieux & nature —
  { v: "לנוח", vT: "Présent", vFr: "se repose", nHe: "בריכה", nFr: "piscine", frT: "L'été, il {V} près de la {N}.", heT: "בקיץ הוא {V} ליד הבריכה." },
  { v: "לשיר", vT: "Présent", vFr: "chante", nHe: "הופעה", nFr: "concert", frT: "Le chanteur {V} au grand {N} du soir.", heT: "הזמר {V} בהופעה הגדולה של הערב." },
  { v: "לבקר", vT: "Présent", vFr: "visite", nHe: "ארמון", nFr: "château", frT: "Le touriste {V} le vieux {N} royal.", heT: "התייר {V} בארמון המלכותי הישן." },
  { v: "למצוא", vT: "Passé", vFr: "a trouvé", nHe: "מערה", nFr: "grotte", frT: "Il {V} un trésor caché dans la {N}.", heT: "הוא {V} אוצר מוסתר במערה." },
  { v: "להתלונן", vT: "Présent", vFr: "se plaint", nHe: "שרב", nFr: "canicule", frT: "Il {V} de la {N} pendant tout l'été.", heT: "הוא {V} על השרב במשך כל הקיץ." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "פרח", nFr: "fleur", frT: "Il {V} une {N} rouge à sa femme.", heT: "הוא {V} פרח אדום לאשתו." },
  { v: "לעלות", vT: "Présent", vFr: "monte", nHe: "סירה", nFr: "bateau", frT: "Il {V} dans le petit {N} du pêcheur.", heT: "הוא {V} על הסירה הקטנה של הדייג." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "מטוס", nFr: "avion", frT: "À l'aéroport, il {V} l'{N} avec impatience.", heT: "בשדה התעופה הוא {V} למטוס בקוצר רוח." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "שלג", nFr: "neige", frT: "En hiver, il {V} la première {N} de l'année.", heT: "בחורף הוא {V} את השלג הראשון של השנה." },
  // — Réemploi de mots connus avec de nouveaux verbes —
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "מלך", nFr: "roi", frT: "Le {N} {V} un ordre à ses soldats.", heT: "ה{N} {V} פקודה לחיילים שלו." },
  { v: "לדבר", vT: "Présent", vFr: "parle", nHe: "שכן", nFr: "voisin", frT: "Il {V} avec son {N} dans l'escalier.", heT: "הוא {V} עם ה{N} במדרגות." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "מנהל", nFr: "patron", frT: "Il {V} son {N} devant le bureau.", heT: "הוא {V} למנהל מול המשרד." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "רופא", nFr: "médecin", frT: "À l'hôpital, il {V} le {N} depuis une heure.", heT: "בבית החולים הוא {V} לרופא כבר שעה." },
  { v: "לחכות", vT: "Présent", vFr: "attend", nHe: "רכבת", nFr: "train", frT: "Le matin, il {V} le {N} sur le quai.", heT: "בבוקר הוא {V} לרכבת ברציף." },
  { v: "לבשל", vT: "Présent", vFr: "cuisine", nHe: "אורז", nFr: "riz", frT: "Le soir, il {V} du {N} avec des légumes.", heT: "בערב הוא {V} אורז עם ירקות." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "מרק", nFr: "soupe", frT: "Quand il fait froid, il {V} une {N} chaude.", heT: "כשקר הוא {V} מרק חם." },
  { v: "לשים", vT: "Présent", vFr: "pose", nHe: "כוס", nFr: "verre", frT: "Il {V} un {N} d'eau sur la table.", heT: "הוא {V} כוס מים על השולחן." },
  { v: "לשים", vT: "Présent", vFr: "pose", nHe: "סכין", nFr: "couteau", frT: "Il {V} le {N} près de l'assiette.", heT: "הוא {V} את הסכין ליד הצלחת." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מזלג", nFr: "fourchette", frT: "Il {V} une {N} propre dans le tiroir.", heT: "הוא {V} מזלג נקי במגירה." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "שטיח", nFr: "tapis", frT: "Il {V} le grand {N} du salon.", heT: "הוא {V} את השטיח הגדול של הסלון." },
  { v: "לשים", vT: "Présent", vFr: "pose", nHe: "מנורה", nFr: "lampe", frT: "Il {V} une {N} sur le bureau.", heT: "הוא {V} מנורה על השולחן." },
  { v: "לעלות", vT: "Présent", vFr: "monte", nHe: "מעלית", nFr: "ascenseur", frT: "Il {V} dans l'{N} avec ses valises.", heT: "הוא {V} במעלית עם המזוודות." },
  { v: "לטפס", vT: "Présent", vFr: "grimpe", nHe: "חומה", nFr: "mur", frT: "Le chat {V} sur le {N} du jardin.", heT: "החתול {V} על החומה של הגינה." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מטריה", nFr: "parapluie", frT: "Sous la pluie, il {V} son {N} noir.", heT: "בגשם הוא {V} את ה{N} השחורה שלו." },
  { v: "לשבור", vT: "Présent", vFr: "casse", nHe: "משקפיים", nFr: "lunettes", frT: "Il {V} ses {N} en tombant.", heT: "הוא {V} את המשקפיים בנפילה." },
  { v: "למכור", vT: "Présent", vFr: "vend", nHe: "טבעת", nFr: "bague", frT: "Il {V} une vieille {N} en or.", heT: "הוא {V} טבעת זהב ישנה." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "שרשרת", nFr: "collier", frT: "Il {V} un beau {N} à sa mère.", heT: "הוא {V} שרשרת יפה לאמא שלו." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "סוודר", nFr: "pull", frT: "Pour l'hiver, il {V} un {N} chaud.", heT: "לחורף הוא {V} סוודר חם." },
  { v: "ללבוש", vT: "Présent", vFr: "porte", nHe: "ז׳קט", nFr: "veste", frT: "Il {V} une {N} élégante au bureau.", heT: "הוא {V} ז׳קט אלגנטי במשרד." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "מכנסיים", nFr: "pantalon", frT: "Il {V} son {N} sale à la main.", heT: "הוא {V} את המכנסיים המלוכלכים ביד." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "חצאית", nFr: "jupe", frT: "Il {V} une {N} bleue pour sa fille.", heT: "הוא {V} חצאית כחולה לבת שלו." },
  { v: "להראות", vHe: "מראה", vT: "Présent", vFr: "montre", nHe: "ירח", nFr: "lune", frT: "Le soir, il {V} la {N} à son enfant.", heT: "בערב הוא {V} את הירח לילד שלו." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "חול", nFr: "sable", frT: "L'enfant {V} un coquillage dans le {N}.", heT: "הילד {V} צדפה בחול." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מאפייה", nFr: "boulangerie", frT: "Le dimanche, il {V} une {N} ouverte.", heT: "ביום ראשון הוא {V} מאפייה פתוחה." },
  { v: "להראות", vHe: "מראה", vT: "Présent", vFr: "montre", nHe: "ציור", nFr: "peinture", frT: "L'artiste {V} sa nouvelle {N} aux amis.", heT: "האמן {V} את הציור החדש שלו לחברים." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מפתח", nFr: "clé", frT: "Le matin, il {V} sa {N} partout dans la maison.", heT: "בבוקר הוא {V} את המפתח בכל הבית." },
  { v: "לשטוף", vT: "Présent", vFr: "lave", nHe: "חלון", nFr: "fenêtre", frT: "Il {V} la {N} sale du salon.", heT: "הוא {V} את החלון המלוכלך של הסלון." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "מחשב", nFr: "ordinateur", frT: "Pour le travail, il {V} un nouvel {N}.", heT: "לעבודה הוא {V} מחשב חדש." },
  { v: "לכתוב", vT: "Présent", vFr: "écrit", nHe: "מכתב", nFr: "lettre", frT: "Il {V} une longue {N} à son vieil ami.", heT: "הוא {V} מכתב ארוך לחבר הוותיק שלו." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מזוודה", nFr: "valise", frT: "À l'aéroport, il {V} sa {N} perdue.", heT: "בשדה התעופה הוא {V} את המזוודה האבודה." },
  { v: "לאהוב", vT: "Présent", vFr: "aime", nHe: "סרט", nFr: "film", frT: "Il {V} beaucoup ce {N} d'action.", heT: "הוא {V} מאוד את הסרט הזה." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "מחברת", nFr: "cahier", frT: "Avant le cours, il {V} son {N} dans le sac.", heT: "לפני השיעור הוא {V} את המחברת בתיק." },
  { v: "לספר", vT: "Présent", vFr: "raconte", nHe: "סיפור", nFr: "histoire", frT: "Le soir, il {V} une belle {N} à ses enfants.", heT: "בערב הוא {V} סיפור יפה לילדים שלו." },
  { v: "להכין", vT: "Présent", vFr: "prépare", nHe: "עוגה", nFr: "gâteau", frT: "Pour la fête, il {V} un grand {N} délicieux.", heT: "למסיבה הוא {V} {N} גדולה וטעימה." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "נעליים", nFr: "chaussures", frT: "Il {V} des {N} neuves pour courir.", heT: "הוא {V} נעליים חדשות לריצה." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "כובע", nFr: "chapeau", frT: "Sous le soleil, il {V} son grand {N}.", heT: "מתחת לשמש הוא {V} את הכובע הגדול שלו." },
  { v: "ללכת", vT: "Présent", vFr: "marche", nHe: "רחוב", nFr: "rue", frT: "Le soir, il {V} dans la {N} calme et vide.", heT: "בערב הוא {V} ברחוב השקט והריק." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "יער", nFr: "forêt", frT: "En automne, il {V} des champignons dans la {N}.", heT: "בסתיו הוא {V} פטריות ביער." },
  { v: "ללמוד", vT: "Présent", vFr: "étudie", nHe: "שפה", nFr: "langue", frT: "Chaque année, il {V} une nouvelle {N}.", heT: "כל שנה הוא {V} שפה חדשה." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "גנב", nFr: "voleur", frT: "Le gardien {V} le {N} sur l'écran de contrôle.", heT: "השומר {V} את הגנב על מסך הבקרה." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "עט", nFr: "stylo", frT: "Pour signer le contrat, il {V} un {N}.", heT: "כדי לחתום על החוזה הוא {V} עט." },
  // — Quelques phrases au passé —
  { v: "לקנות", vT: "Passé", vFr: "a acheté", nHe: "מטוס", nFr: "avion", frT: "Le riche homme {V} un petit {N} privé.", heT: "האיש העשיר {V} מטוס פרטי קטן." },
  { v: "לראות", vT: "Passé", vFr: "a regardé", nHe: "הופעה", nFr: "concert", frT: "Hier soir, il {V} un beau {N} en plein air.", heT: "אתמול בערב הוא {V} הופעה יפה באוויר הפתוח." },
  { v: "למצוא", vT: "Passé", vFr: "a trouvé", nHe: "מפתח", nFr: "clé", frT: "Enfin, il {V} sa {N} sous le lit.", heT: "סוף סוף הוא {V} את המפתח מתחת למיטה." },
  { v: "לשלוח", vT: "Passé", vFr: "a envoyé", nHe: "פרח", nFr: "fleur", frT: "Pour la fête des mères, il {V} de belles {N}.", heT: "ליום האם הוא {V} פרחים יפים." },
  { v: "לאכול", vT: "Passé", vFr: "a mangé", nHe: "פאי", nFr: "tarte", frT: "Au dessert, il {V} une {N} aux fraises.", heT: "בקינוח הוא {V} פאי תותים." },
  { v: "לבקר", vT: "Passé", vFr: "a visité", nHe: "מערה", nFr: "grotte", frT: "Pendant le voyage, il {V} une {N} très ancienne.", heT: "במהלך הטיול הוא {V} במערה עתיקה מאוד." },
  { v: "לפגוש", vT: "Passé", vFr: "a rencontré", nHe: "תייר", nFr: "touriste", frT: "Au marché, il {V} un {N} allemand sympathique.", heT: "בשוק הוא {V} תייר גרמני נחמד." },
  { v: "לצבוע", vT: "Passé", vFr: "a peint", nHe: "סירה", nFr: "bateau", frT: "L'été dernier, il {V} son vieux {N} en bleu.", heT: "בקיץ שעבר הוא {V} את הסירה הישנה בכחול." },
  // — Encore quelques présents variés —
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "עגבנייה", nFr: "tomate", frT: "En été, il {V} une {N} fraîche du jardin.", heT: "בקיץ הוא {V} עגבנייה טרייה מהגינה." },
  { v: "לתת", vT: "Présent", vFr: "donne", nHe: "גזר", nFr: "carotte", frT: "Il {V} une {N} au petit lapin.", heT: "הוא {V} גזר לארנב הקטן." },
  { v: "לקנות", vT: "Présent", vFr: "achète", nHe: "ריבה", nFr: "confiture", frT: "Au marché, il {V} une {N} sucrée aux fraises.", heT: "בשוק הוא {V} ריבה מתוקה." },
  { v: "לאהוב", vT: "Présent", vFr: "aime", nHe: "בריכה", nFr: "piscine", frT: "En été, il {V} beaucoup la grande {N}.", heT: "בקיץ הוא {V} מאוד את הבריכה הגדולה." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "גמל", nFr: "chameau", frT: "Au zoo, il {V} un grand {N} brun.", heT: "בגן החיות הוא {V} גמל חום גדול." },
  { v: "לראות", vT: "Présent", vFr: "voit", nHe: "צב", nFr: "tortue", frT: "Près de l'étang, il {V} une petite {N}.", heT: "ליד האגם הוא {V} צב קטן." },
  { v: "לחפש", vT: "Présent", vFr: "cherche", nHe: "רועה", nFr: "berger", frT: "Dans la montagne, il {V} un vieux {N}.", heT: "בהר הוא {V} רועה זקן." },
  { v: "להסביר", vT: "Présent", vFr: "explique", nHe: "לקוח", nFr: "client", frT: "Le vendeur {V} le prix au {N}.", heT: "המוכר {V} את המחיר ל{N}." },
  { v: "לאכול", vT: "Présent", vFr: "mange", nHe: "חסה", nFr: "laitue", frT: "Avec le poulet, il {V} de la {N} verte et fraîche.", heT: "עם העוף הוא {V} חסה ירוקה וטרייה." },
];
